tasks:
  - init: npm install
    command: export TZ="Asia/Tokyo"
    command: eval $(gp env -e) && npm run start
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==